export const dummy_product = [
  {
    id: 1,
    name: 'boat1',
    color: 'matBlack',
    isOff: true,
    offPercentage: 10,
    price: 60000.00,
    image: require('../assests/images/products/boat1.png'),
    productImageList: [
      require('../assests/images/products/boat1.png'),
      require('../assests/images/products/boat2.png'),
      require('../assests/images/products/boat3.png'),
    ],
    isAvaliable: true,
  },
  {
    id: 2,
    name: 'boatrocks',
    color: 'red',
    price: 60000.00,
    isOff: false,
    offPercentage: 10,
    image: require('../assests/images/products/boatrockerz1.png'),
    productImageList: [
      require('../assests/images/products/boatrockerz1.png'),
      require('../assests/images/products/boatrockerz2.png'),
      require('../assests/images/products/boatrockerz3.png'),
    ],
    isAvaliable: true,
  },
  {
    id: 3,
    name: 'boatAirpod',
    color: 'nebula',
    isOff: true,
    offPercentage: 10,
    price: 60000.00,
    image: require('../assests/images/products/boatairpods1.png'),
    productImageList: [
      require('../assests/images/products/boatairpods1.png'),
      require('../assests/images/products/boatairpods2.png'),
      require('../assests/images/products/boatairpods3.png'),
    ],
    isAvaliable: true,
  },
  {
    id: 4,
    name: 'SkullCandy',
    color: 'silver',
    isOff: false,
    offPercentage: 10,
    price: 60000.00,
    image: require('../assests/images/products/boatbassheads1.png'),

    productImageList: [
      require('../assests/images/products/boatbassheads1.png'),
      require('../assests/images/products/boatbassheads2.png'),
      require('../assests/images/products/boatbassheads3.png'),
    ],
    isAvaliable: true,
  },
  {
    id: 5,
    name: 'Iphone 15',
    color: 'silver',
    isOff: true,
    offPercentage: 10,
    price: 60000.00,
    image: require('../assests/images/products/iphone.jpg'),
    productImageList: [
      require('../assests/images/products/iphone.jpg'),
      require('../assests/images/products/iphone.jpg'),
      require('../assests/images/products/iphone.jpg'),
    ],
    isAvaliable: true,
  },
  {
    id: 6,
    name: 'boatbassHeads',
    color: 'silver',
    isOff: false,
    offPercentage: 10,
    price: 60000.00,
    image: require('../assests/images/products/boatbassheads1.png'),
    productImageList: [
      require('../assests/images/products/boatbassheads1.png'),
      require('../assests/images/products/boatbassheads2.png'),
      require('../assests/images/products/boatbassheads3.png'),
      require('../assests/images/products/boatbassheads3.png'),
    ],
    isAvaliable: false,
  },
];
